### ISSUE TITLE
Issue with Azure Files mount

### ISSUE THREAD

**Issue by artisticcheese** [emberstack/docker-sftp#103]
Is there a solution for using Azure FIles mount in AKS? Getting error below when trying to 
sshd - bad ownership or modes for chroot directory component "/home/". Config is below

```
      containers:
        - name: sftp
          # change this
          image: emberstack/sftp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 22
          volumeMounts:
            - name: sftp-config
              mountPath: "/app/config/sftp.json"
              subPath: sftp.json
              readOnly: true
            - name: sftp
              mountPath: "/home/"
              readOnly: false
      volumes:
        - name: sftp
          azureFile:
            secretName: fileshare-secret
            shareName: sftp
            readOnly: false
        - name: sftp-config
          secret:
            defaultMode: 0600
            secretName: sftp-secret
            items:
              - key: sftp.json
                path: sftp.json
```
