### ISSUE TITLE
Basic yaml values for full read/write access to a mounted volume?

### ISSUE THREAD

**Issue by Dunge** [emberstack/docker-sftp#137]
Hello,

Sorry if this question seem simple, but I'm out of my depth here. I'm just trying to add a sftp service that serves my existing kubernetes pvc and want full read/write access.

Here's the values.yaml file I managed to write up to now:

```
configuration:
  Global:
    Chroot:
      Directory: "%h"
      StartPath: /
  Directories:
    - /
  Users:
    - Username: myuser
      Password: mypass
      UID: 1000
      GID: 100

storage:
  volumes:
    - name: sftp-storage
      persistentVolumeClaim:
        claimName: jl-data

  volumeMounts:
    - name: sftp-storage
      mountPath: "/home/myuser/"
```

I can login to the service and see the files, but I can't modify or upload anything, I receive a "Permission denied" error.

I don't quite grasp the concept of what Chroot is, what %h mean, and what the UID/GID values should be used (I got those by getting in a bash console on the pod and using  id -u myuser / id -g myuser).
