### ISSUE TITLE
Global.Chroot is not respected

### ISSUE THREAD

**Issue by freddyli** [emberstack/docker-sftp#152]
I would like to change the default `Global.Chroot` to something else, like: `%h/sftp`. No other `Chroot` configuration in `Users`. Still, the users get configured with the default `Chroot` of `%h`.

I think I have some hints to the root cause below.

My config is:

```json
{
    "Global": {
        "Chroot": {
            "Directory": "%h/sftp"
        }
    },
    "Users": [
        {
            "Username": "demo",
            "Password": "demo",
        }
    ]
}
```

I wse docker compose:

```yaml
  sftp:
    image: "emberstack/sftp:5.1.71"
    ports:
      - "22:22"
    volumes:
      - ./secrets/sftp.json:/app/config/sftp.json:ro
      - ./volumes/demo/something/:/home/demo/sftp/something/
```

Maybe I am overlooking something and barking up the wrong tree. But after a quick look through the code, here are my thoughts in screenshots:

![240809-145311](https://github.com/user-attachments/assets/9bc4f0db-fab6-413d-a363-199ad6e04ef5)
![240809-145331](https://github.com/user-attachments/assets/f29f2dc7-017b-47f8-8b6e-ba6a5c5baa74)
![240809-145249](https://github.com/user-attachments/assets/7035ccb8-a595-4359-a357-09c1eaf7ddd5)
![240809-145410](https://github.com/user-attachments/assets/c2e6aefc-a1dd-44fe-bec7-3a7a771446dd)
![240809-145458](https://github.com/user-attachments/assets/a0fbf962-f1e4-4aad-a454-483a8056fc55)
