### ISSUE TITLE
Health Check feature

### ISSUE THREAD

**Issue by jrichardsz** [emberstack/docker-sftp#156]
## Current Behavior

There is not a provided health check to be used with docker compose

## Desired Behavior

Any strategy to perform a simple health check to know when the container is healthy and ready to work

## Workaround

I created another image  in which I installed

```
apt-get update && apt-get install -y netcat
```

The this health check can be used

```
    healthcheck: 
        test: nc 127.0.0.1 22 -z
        interval: 1s
        retries: 30   
```

## Idea

If you can provide a simple http port like

```
/health
```

It would not be required the netcat installation
