### ISSUE TITLE
Unable to configure custom users

### ISSUE THREAD

**Issue by micos76** [emberstack/docker-sftp#20]
Hi guys,
I am bit new with Helm Charts and was giving yours a try.
Installing this chart on a Minikube running in MacOS with the following configuration in the chart values:

```
configuration:
  Global:
    Chroot:
      Directory: "%h"
      StartPath: "sftp"

    Directories: "sftp"

  Users:
    Username: "demo"
    Password: "demo"
```

Just trying to reproduce your default configuration (tried other users as well) and all seems fine apart from the fact that when typing the password the login will not work.

This is the config mounted in the container:

```
root@sftp-646d99b78c-wrq74:/app# cat config/sftp.json 

{
  "Global": {
    "Chroot": {
      "Directory": "%h",
      "StartPath": "sftp"
    },
    "Directories": "sftp"
  },
  "Users": {
    "Password": "demo",
    "Username": "demo"
  }
```

This is the log message from *dmesg*:

```
[55973.919899] audit: type=1112 audit(1590171434.045:478): pid=27807 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='op=login acct=28696E76616C6964207573657229 exe="/usr/sbin/sshd" hostname=? addr=172.17.0.1 terminal=sshd res=failed'
[55974.845652] audit: type=1109 audit(1590171434.971:479): pid=27807 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='op=PAM:bad_ident grantors=? acct="?" exe="/usr/sbin/sshd" hostname=172.17.0.1 addr=172.17.0.1 terminal=ssh res=failed'
```

Any help appreciated to understand if I am missing something stupid.

Thanks
Marco

**Comment by smiller171** [comment]
You want:
```yaml
configuration:
  Users:
    - Username: "demo"
      Password: "demo"
```
It's a list of objects, not a single object.
