### ISSUE TITLE
Nodeport can not be set

### ISSUE THREAD

**Issue by phoenix-bjoern** [emberstack/docker-sftp#78]
In `service.yaml` the service type `NodePort` can be set. However, this will assign a random port.
In order to specify a fixed port within the allowed port range it is required to set the `nodePort` in the `values.yaml` and render it in the template (see https://kubernetes.io/docs/concepts/services-networking/service/#nodeport).

values.yaml:
```
service:
  type: NodePort
  nodePort: 32222
```

service.yaml:
```
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
```

**Comment by phoenix-bjoern** [comment]
As a temporary workaround you can change the nodePort, which is automatically assigned by K8S, with a patch:
```
  kubectl patch svc -n <namespace> sftp --type='json' -p '[{"op":"replace","path":"/spec/ports/0/nodePort","value":32222}]'
```
If you set `fullnameOverride: sftp` in `values.yaml` the service name is easier to reference on the CLI.

**Comment by phoenix-bjoern** [comment]
This is still an open issue and I would appreciate if this feature could be added. Let me know if you want me to create a PR.

**Comment by benjaminpreiss** [comment]
Should anyone use `helmfile` here - this is how you can use `kustomize` to apply `nodePort`:

```yaml
#helmfile.yaml
# ...
releases:
    - name: sftp
      namespace: sftp
      chart: emberstack/sftp
      version: ^5.1.71
      createNamespace: true
      values:
        # ...
        - service:
            type: NodePort
      strategicMergePatches:
        - apiVersion: v1
          kind: Service
          metadata:
              name: sftp
          spec:
              $patch: replace
              type: NodePort
              ports:
                  - port: 22
                    nodePort: 30022
                    protocol: TCP
```
